// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2mw7GazPSO1sKtFKl3ir2aHaFHVBWl34',
    appId: '1:1031319272692:web:b34ad76d9ec0cab565f2a1',
    messagingSenderId: '1031319272692',
    projectId: 'si-b-881ac',
    authDomain: 'si-b-881ac.firebaseapp.com',
    storageBucket: 'si-b-881ac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApSmAodrRk9AjlMSe_boxOp-GzvDLxTks',
    appId: '1:1031319272692:android:a9efcafadda02e7d65f2a1',
    messagingSenderId: '1031319272692',
    projectId: 'si-b-881ac',
    storageBucket: 'si-b-881ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0kvec6sni0SqX80p14EsxpNm-d0fqKDU',
    appId: '1:1031319272692:ios:e7600a28f252bc1e65f2a1',
    messagingSenderId: '1031319272692',
    projectId: 'si-b-881ac',
    storageBucket: 'si-b-881ac.firebasestorage.app',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0kvec6sni0SqX80p14EsxpNm-d0fqKDU',
    appId: '1:1031319272692:ios:e7600a28f252bc1e65f2a1',
    messagingSenderId: '1031319272692',
    projectId: 'si-b-881ac',
    storageBucket: 'si-b-881ac.firebasestorage.app',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2mw7GazPSO1sKtFKl3ir2aHaFHVBWl34',
    appId: '1:1031319272692:web:f6cd0220c17574b865f2a1',
    messagingSenderId: '1031319272692',
    projectId: 'si-b-881ac',
    authDomain: 'si-b-881ac.firebaseapp.com',
    storageBucket: 'si-b-881ac.firebasestorage.app',
  );
}
